[package]
name = "my_runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-channel = "1.9.0"
async-lock = "2.8.0"
futures = "0.3.28"
num_cpus = "1.16.0"
scoped-tls = "1.0.1"
