name: Rust

on:
  push:
    branches:
      - 'hw1'
  pull_request:
    branches:
      - 'hw1'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Upgrade Rust
      run: rustup update
    - name: Build, Test, Clippy all
      run: sh -x ./scripts/ci.sh