name: Rust

on:
  push:
    branches:
      - 'hw5'
  pull_request:
    branches:
      - 'hw5'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Nightly Rust
      run: rustup toolchain install nightly
    - name: Use Nightly Rust
      run: rustup default nightly
    - name: Install Volo
      run: cargo install volo-cli
    - name: Build, Test, Clippy all
      run: sh -x ./.scripts/ci.sh
